### ISSUE TITLE
Update to recent SpongeAPI changes

### ISSUE THREAD

**Issue by Minecrell** [LapisBlue/Commons#6]
We should design Commons similar to SpongeAPI, at the end one of the goals of Commons is to extend the SpongeAPI where it is too limited, with features not needed directly in the SpongeAPI but useful for a lot of plugins. That's why we should also use a similar code style (e.g. using Optional) like Sponge.

For that we should go through our current drafts and update them as needed. We also need to discuss which APIs are still needed and which changes we need to make.

For that, @falkreon should probably look at his emails and reply if possible.. :P

**Comment by Minecrell** [comment]
@AesenV Do you still have contact to @falkreon? We really need his answer to continue working so if you still have contact to him it would be nice if you could ask him to read his emails.

**Comment by AesenV** [comment]
Yes, I do. I'll tell him when I get the chance.

**Comment by Minecrell** [comment]
@AesenV Thanks :)

**Comment by Minecrell** [comment]
@AesenV Did you had the chance to ask him about this?

**Comment by AesenV** [comment]
@Minecrell Yes, he seems to have lost interest in Sponge. I'll keep trying to get him to at least talk to you, even if he's not interested in the project anymore.

**Comment by IDragonfire** [comment]
Can you make a list of questions? Maybe I can answer some?

**Comment by Minecrell** [comment]
@AesenV At the end, the email is simply about asking him if he's planning to come back. We need an answer on that because we decided to wait with the discussions and development until Sponge is more mature. Then he wanted to come back and continue Commons with us.

While I would love to see @falkreon back (our discussions were always interesting, it was a good time...) I know interests can change and that's nothing bad. If he doesn't want to contribute anymore we'll need to continue on our own. I just didn't want to start again without asking him. If he's not interested anymore that's enough already although I hoped to hear this from him at least..

Do you mean he seems to be not interested in just Sponge or also Commons together with that? Then that would be already enough I guess...

Thanks a lot for asking him about that.

@IDragonfire As you can see the email was not about questions for Commons but just if he wants to return. I doubt you can answer that. :P

**Comment by AesenV** [comment]
@Minecrell He didn't make it terribly clear, but I feel like he'd still be
fine with discussing things, just not dedicating a ton of time to it.
He did say Sponge specifically, though.
If Sponge makes a full release, he might become interested in it again. I
think a lot of us are just losing hope in Sponge since the hype has died
down.

**Comment by Minecrell** [comment]
@AesenV Well if he wants to discuss things we're in #lapis so this is where he can find us if he wants to. I guess this is solved for now. Thanks again for contacting him.
